### ISSUE TITLE
How do train this model with another language like bangla? Or how do I Fine tune the model with bangla datasets?

### ISSUE THREAD

**Issue by FarhadGazi** [Emotional-Text-to-Speech/dl-for-emo-tts#2]
Hello there,
I am doing my final year project which is similar to this model but I want to Build an emotional tts in Bangla. And I want to run the model in colab. Your response will be appreciated.

**Comment by jinny1208** [comment]
@FarhadGazi Hi, this is a different question, but were you able to run the provided ipynb file in colab? I cant get the demo to work and continue to get the error "FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/ssrn.pth'"

**Comment by madaanpulkit** [comment]
> @FarhadGazi Hi, this is a different question, but were you able to run the provided ipynb file in colab? I cant get the demo to work and continue to get the error "FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/ssrn.pth'"

#3

**Comment by madaanpulkit** [comment]
> Hello there, I am doing my final year project which is similar to this model but I want to Build an emotional tts in Bangla. And I want to run the model in colab. Your response will be appreciated.

If you have enough data you can train from scratch on the same model pipeline, if not fine-tuning might be the best way forward. Do go through the [README.md](../#contents) to understand what suits your case
