### ISSUE TITLE
google drive links expired

### ISSUE THREAD

**Issue by codehustling** [Emotional-Text-to-Speech/dl-for-emo-tts#3]
Hi, could you link me up to the trained model files(.pth)? The ones mentioned in Google Colab doesn't seem to exist anymore or the public don't have the permission to view the files probably?

I request you to upload those models to any git LFS supported sites like HuggingFace. A quick response will be highly appreciated

@Pranav-Jain @madaanpulkit @brihijoshi @justachetan

**Comment by wei-m-teh** [comment]
Hi, same here, I am looking to test out the model but getting access denied when the notebook tries to download the trained models.

**Comment by madaanpulkit** [comment]
Hi, sorry folks, we recently had a change in our institute drive storage policy so we had to move TBs worth of data around. Let me see what can be done to make it available again.

**Comment by madaanpulkit** [comment]
While we are working on changing the colab notebook links, you can use the updated links given in the [README.md](../#reproducibility-and-code), pick up the checkpoint you like, and replace with the link in the downloads section. 

Refer to [this gdown tutorial](https://clay-atlas.com/us/blog/2021/07/01/python-en-gdown-package-download-file-google-drive/) for getting download links from view links.
