### ISSUE TITLE
can get trained model. url is not active

### ISSUE THREAD

**Issue by sachinlobo11** [Emotional-Text-to-Speech/dl-for-emo-tts#5]

**Comment by rsandx** [comment]
Same issue here, got 404 error (The requested URL was not found on this server) when trying to download the trained models on Google Drive.

**Comment by justachetan** [comment]
Hi, can you please try again? The demo_models link in the README seems to be working for me.

**Comment by rsandx** [comment]
The demo models link in the README does work, it's the urls in Demo_DL_Based_Emotional_TTS.ipynb wrong, so you can't just run the notebook to try, it'd be helpful if you can fix the urls there.

**Comment by dilerbatu** [comment]
same problem

**Comment by justachetan** [comment]
URLs are now updated and should be working. Closing for now. Feel free to open if this persists.
